# Generated by Django 5.0.7 on 2024-08-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficial',
            name='nui',
            field=models.IntegerField(unique=True),
        ),
    ]
