# Generated by Django 5.0.7 on 2024-08-05 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_infraccion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infraccion',
            old_name='vehiculo',
            new_name='vehiculo_id',
        ),
    ]
