# Generated by Django 5.0.7 on 2024-08-05 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_vehiculo_infraccion_vehiculo_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infraccion',
            old_name='vehiculo_id',
            new_name='vehiculo',
        ),
    ]
